% -------------------------------------------------------------------
%  Generated by MATLAB on 6-Nov-2021 21:07:23
%  MATLAB version: 9.11.0.1769968 (R2021b)
% -------------------------------------------------------------------
saveVarsMat = load('wzgw_pro1_2.mat');

wzgwdanepro1 = saveVarsMat.wzgwdanepro1; % <1x1 table> unsupported class

clear saveVarsMat;
